# Generated by Django 3.1.4 on 2021-06-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_auto_20210613_1509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('staff', '0002_staff_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstock',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.storage'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.address'),
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.AddField(
            model_name='bookgenre',
            name='book_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bookdescription'),
        ),
        migrations.AddField(
            model_name='bookgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.genre'),
        ),
        migrations.AddField(
            model_name='bookdescription',
            name='book_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.bookstatus'),
        ),
        migrations.AddField(
            model_name='author',
            name='fullname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.fullname'),
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('electronic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.electronic')),
                ('width', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('type_of_appliance', models.CharField(max_length=100)),
            ],
            bases=('product.electronic',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('electronic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.electronic')),
                ('dimension', models.FloatField()),
                ('device_type', models.CharField(max_length=100)),
            ],
            bases=('product.electronic',),
        ),
        migrations.AddField(
            model_name='clothing',
            name='type_of_clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clothingtype'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookDescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bookdescription'),
        ),
    ]
