# Generated by Django 3.1.4 on 2021-06-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_off', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=100)),
                ('additional_fee', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateTimeField(max_length=100)),
                ('receive_date', models.DateTimeField(max_length=100)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.payment')),
                ('creditNumber', models.BigIntegerField()),
            ],
            bases=('order.payment',),
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.payment')),
            ],
            bases=('order.payment',),
        ),
        migrations.CreateModel(
            name='DomesticShip',
            fields=[
                ('shipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.shipment')),
                ('distance', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
            ],
            bases=('order.shipment',),
        ),
        migrations.CreateModel(
            name='GlobalShip',
            fields=[
                ('shipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.shipment')),
                ('country', models.CharField(max_length=100)),
                ('delivery_type', models.CharField(max_length=100)),
            ],
            bases=('order.shipment',),
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shipment')),
            ],
        ),
    ]
